# Generated by Django 2.2.3 on 2019-08-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_listings_textracted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jreturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('user', models.IntegerField(max_length=30)),
            ],
        ),
    ]
