# Generated by Django 2.2.4 on 2019-08-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jreturns'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='photo_1',
            field=models.ImageField(blank=True, default='placeholder', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='photo_2',
            field=models.ImageField(blank=True, default='placeholder', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='photo_3',
            field=models.ImageField(blank=True, default='placeholder', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='photo_4',
            field=models.ImageField(blank=True, default='placeholder', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='photo_5',
            field=models.ImageField(blank=True, default='placeholder', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='jreturns',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_main',
            field=models.ImageField(blank=True, default='placeholder', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='textracted',
            field=models.BooleanField(default=True),
        ),
    ]
