# Generated by Django 2.2.4 on 2019-08-31 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
