# Generated by Django 2.2.4 on 2019-09-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='reading',
            field=models.IntegerField(null=True),
        ),
    ]
