# Generated by Django 2.2.4 on 2019-09-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190906_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='textracted',
            field=models.BooleanField(default=False),
        ),
    ]
