# Generated by Django 2.2.4 on 2019-09-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190909_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jreturns',
            name='file',
        ),
        migrations.AddField(
            model_name='jreturns',
            name='file_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
