# Generated by Django 2.2.4 on 2019-09-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190909_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200)),
                ('photo_id', models.IntegerField(null=True)),
                ('user', models.IntegerField()),
            ],
        ),
    ]
